import { json, preflight } from '@/lib/api/http';

/** GET /api/v1 — endpoint index (full reference: docs/API.md). */
export function GET(): Response {
  return json({
    name: 'Storefront API',
    version: 'v1',
    docs: 'docs/API.md',
    conventions: {
      auth: 'Authorization: Bearer <accessToken> from POST /auth/token (or the web session cookie)',
      market: '?market=US|IN (default US) or X-Market header',
      guestCart: 'X-Cart-Token header; minted on the first guest cart write and returned in the X-Cart-Token response header',
      money: 'integer minor units (cents / paise) with an ISO currency code',
      errors: '{ error: { code, message, detail? } } with a matching HTTP status',
    },
    endpoints: [
      'POST   /auth/signup',
      'POST   /auth/token',
      'POST   /auth/refresh',
      'GET    /me',
      'GET    /me/plus',
      'POST   /me/plus',
      'DELETE /me/plus',
      'GET    /me/balance',
      'POST   /me/balance/redeem',
      'POST   /me/balance/demo-card',
      'GET    /me/gift-cards?limit=',
      'POST   /me/gift-cards',
      'GET    /me/reviews',
      'GET    /categories',
      'GET    /products?q=&dept=&brand=&rating=&deal=&sort=&page=',
      'GET    /suggest?q=',
      'GET    /products/:id',
      'GET    /products/:id/bought-together',
      'GET    /products/:id/insights?summarize=',
      'GET    /products/:id/reviews?limit=&offset=',
      'POST   /products/:id/reviews',
      'DELETE /reviews/:id',
      'POST   /reviews/:id/helpful',
      'POST   /reviews/:id/report',
      'GET    /products/:id/questions?q=&limit=&offset=',
      'POST   /products/:id/questions',
      'DELETE /questions/:id',
      'POST   /questions/:id/answers',
      'DELETE /answers/:id',
      'POST   /answers/:id/helpful',
      'GET    /coupons',
      'POST   /products/:id/coupon',
      'DELETE /products/:id/coupon',
      'GET    /cart',
      'DELETE /cart',
      'POST   /cart/items',
      'PATCH  /cart/items/:productId',
      'DELETE /cart/items/:productId',
      'POST   /cart/merge',
      'GET    /orders',
      'POST   /orders',
      'GET    /orders/buy-again?limit=',
      'GET    /orders/:id',
      'POST   /orders/:id/cancel',
      'GET    /orders/:id/returns',
      'POST   /orders/:id/returns',
      'POST   /returns/:id/cancel',
      'GET    /addresses',
      'POST   /addresses',
      'GET    /addresses/:id',
      'PATCH  /addresses/:id',
      'DELETE /addresses/:id',
      'POST   /addresses/:id/default',
      'GET    /collections',
      'POST   /collections',
      'GET    /collections/:id',
      'PATCH  /collections/:id',
      'DELETE /collections/:id',
      'POST   /collections/:id/items',
      'DELETE /collections/:id/items/:productId',
      'POST   /collections/:id/items/:productId/move',
      'POST   /collections/:id/share',
      'DELETE /collections/:id/share',
      'GET    /lists/:token',
      'GET    /ai/status',
      'POST   /ai/parse-query',
      'POST   /ai/profile',
      'POST   /ai/compare',
      'GET    /admin/products?status=&q=&category=&page=',
      'POST   /admin/products',
      'GET    /admin/products/:id',
      'PATCH  /admin/products/:id',
      'DELETE /admin/products/:id',
      'GET    /admin/categories',
      'POST   /admin/categories',
      'PATCH  /admin/categories/:slug',
      'DELETE /admin/categories/:slug',
      'GET    /admin/orders?filter=&q=&page=',
      'GET    /admin/orders/:id',
      'POST   /admin/orders/:id/ship',
      'POST   /admin/orders/:id/deliver',
      'POST   /admin/orders/:id/cancel',
      'POST   /admin/orders/:id/refund',
      'GET    /admin/returns?filter=&page=',
      'GET    /admin/returns/:id',
      'POST   /admin/returns/:id/receive',
      'POST   /admin/returns/:id/reject',
      'POST   /admin/returns/:id/refund',
      'GET    /admin/reviews?view=&page=',
      'POST   /admin/reviews/:id/keep',
      'POST   /admin/reviews/:id/hide',
      'DELETE /admin/reviews/:id',
      'GET    /admin/questions?view=&page=',
      'DELETE /admin/questions/:id',
      'DELETE /admin/answers/:id',
      'POST   /webhooks/stripe',
    ],
  });
}

export const OPTIONS = preflight;
